# Generated by Django 2.1.7 on 2019-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190329_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='links',
            new_name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
